# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://yoursite.com
title: proxl - Visualize and Share Protein Cross-linking Proteomics Data
email: proxl-help@yeastrc.org
author: Michael Riffle
description: > # "Write an awesome description for your new site here. 
  Proxl is a platform for analyzing, visualizing, and sharing protein cross-linking mass spectrometry proteomics data.
copyright: 'Copyright &copy; 2017 Michael Riffle. All Rights Reserved.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: question-circle
    url: http://www.yeastrc.org/proxl_docs/
  - title: github
    url: https://github.com/IronSummitMedia/startbootstrap
  - title: linkedin
    url: 
